test-verifier: New image for use in K8sVerifier test
cilium/image-tools pull request #124
Opened 2021-05-20 14:47 UTC by pchaigno

This new image will be used in the K8sVerifier test in replacement for cilium-builder. It includes a custom patch of iproute2 to work around issues with the log buffer size.

2021-05-21 09:43 UTC, qmonnet approved these changes
Seems all in order to me.

2021-05-27 02:38 UTC, aanm requested changes

2021-05-27 02:38 UTC, aanm commented on images/test-verifier/Dockerfile
> +FROM ubuntu:20.04
`FROM docker.io/library/ubuntu:20.04@sha256:b4aa552dd3f2ed84f3214b0e8add3648aee0205ef58295c92fe0899f96ad8755`

2021-05-28 01:43 UTC, aanm approved these changes

2021-05-28 01:43 UTC, merged