allow C's _Static_assert
cilium/image-tools pull request #199
Opened 2023-01-12 09:25 UTC by kkourt

Add an exception for _Static_assert in the CamelCase tests.

2023-01-13 09:31 UTC, qmonnet requested changes
Typo to fix in the README, but looks good otherwise. I don't see any solution for allowing `_Static_assert` other than patching the Perl script indeed.

2023-01-13 09:31 UTC, qmonnet commented on images/checkpatch/README.md
> +  even though it is is camel-cased.
```suggestion
  even though it is camel-cased.
```

2023-01-13 10:22 UTC, kkourt commented
> Typo to fix in the README, but looks good otherwise. I don't see any solution for allowing `_Static_assert` other than patching the Perl script indeed.

Thanks! pushed typo, squashed, and pushed.

2023-01-13 10:22 UTC, qmonnet approved these changes
Thanks!

2023-01-16 07:21 UTC, kkourt commented
@qmonnet do you permissions to merge this? (I do not)

2023-01-16 09:10 UTC, NikAleksandrov approved these changes

2023-01-16 09:34 UTC, merged