Fix: update readme after new tagging mechanic
cilium/image-tools pull request #294
Opened 2024-08-05 15:58 UTC by Artyop

Following the pr #286, update of the README.md about how the tagging mechanic works

2024-08-06 12:56 UTC, qmonnet requested changes
Small nits in the wording, but looks good otherwise, thanks!

2024-08-06 12:56 UTC, qmonnet commented on README.md
> +All images get automatic tags based on the latest commit of the image directory. Tags used to be done through unique [git tree object hash](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects) b
It's sha1 and not sha256, isn't it?

```suggestion
All images get automatic tags based on the latest commit of the image directory. Tags used to be based on unique [git tree object hash](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects), but due to setting up renovate to automatically update images, and the inability to order sha1 values by time, the new tagging system uses a combination of the timestamp and the short sha1 of the latest commit for the image directory, using the [git log command with the image directory as a path parameter](https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History).
```

2024-08-06 12:56 UTC, qmonnet commented on README.md
> +- image build is defined by the last commit that has modified the image directory
```suggestion
- image build is defined by the last commit that modified the image directory
```

2024-08-06 15:46 UTC, Artyop commented
> Small nits in the wording, but looks good otherwise, thanks!

thank you, applied the fix !

2024-08-06 16:03 UTC, qmonnet approved these changes
Thank you! For future PRs, please squash the two commits together (do keep logical commits in the PR, but review fixes should not stand out as separate commits), and no need to keep the `co-authored-by` for trivial review fixes :slightly_smiling_face:

2024-08-07 08:26 UTC, Artyop commented
> Thank you! For future PRs, please squash the two commits together (do keep logical commits in the PR, but review fixes should not stand out as separate commits), and no need to keep the `co-authored-by` for trivial review fixes 🙂

fixed that too, thanks a lot for the review !

2024-08-07 09:40 UTC, qmonnet commented
I can't merge without the missing reviews. I'll request one from Tobias, as I think Daniel is out.

2024-08-07 09:53 UTC, tklauser approved these changes

2024-08-07 09:53 UTC, merged